# Reproducible Research: Peer Assessment 1

## Load necessary libraries

library(ggplot2)
library(knitr)

## Loading and preprocessing the data

Let's read in the data first. The data is in a compressed file called "activity.zip" included with this project. First unzip that file to your working directory, which will reveal a CSV format file ("activity.csv"). Then we can load and check the data as seen right below here.

```{r}
data <- read.csv("activity.csv")
head(data)
```

Now let's process/transform the data (if necessary) into a format suitable for our analysis. In other words, let's tidy it up.

## What is mean total number of steps taken per day?

For this part of the assignment, we ignore the missing values in the dataset. Here is a histogram of the total number of steps taken each day:



Calculate and report the mean and median total number of steps taken per day.


## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
